title: Rock Paper Scissors YSC
description: All I want is a smile from you. Let's play!
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
google_ad_client: ca-pub-2718185808906795
